name: mrs_sdk_flutter
description: MRS SDK for Flutter
version: 0.1.0
homepage: https://mrs-electronics.dev
repository: https://github.com/mrs-electronics-inc/mrs-sdk-flutter
documentation: https://flutter.mrs-electronics.dev
issue_tracker: https://github.com/mrs-electronics-inc/mrs-sdk-flutter/issues

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
