name: mrs_sdk_flutter
description: Official Flutter package for integrating mobile apps with MRS Electronic products and services.
version: 0.5.2
homepage: https://mrs-electronics.dev
repository: https://github.com/mrs-electronics-inc/mrs-sdk-flutter
documentation: https://flutter.mrs-electronics.dev
issue_tracker: https://github.com/mrs-electronics-inc/mrs-sdk-flutter/issues

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  analysis_server_plugin: ^0.3.7
  analyzer: ^10.0.1
  http: ^1.6.0
  mqtt_client: ^10.11.9

dev_dependencies:
  analyzer_testing: ^0.1.9
  flutter_lints: ^6.0.0
  test: ^1.31.0
flutter:
