name: mrs_sdk_flutter_lints
description: Analyzer plugin providing lint rules for MRS SDK Flutter projects.
version: 0.6.1
homepage: https://mrs-electronics.dev
repository: https://github.com/mrs-electronics-inc/mrs-sdk-flutter
documentation: https://flutter.mrs-electronics.dev
issue_tracker: https://github.com/mrs-electronics-inc/mrs-sdk-flutter/issues

environment:
  sdk: ^3.11.0

dependencies:
  analysis_server_plugin: ^0.3.7
  analyzer: ^10.0.1

dev_dependencies:
  analyzer_testing: ^0.1.9
  lints: ^6.0.0
  test: ^1.31.0
